server.shutdown: GRACEFUL

logging:
  level:
    org.springframework.cloud.gateway.filter: trace

# default circuit breaker config without Bulkhead
# https://github.com/spring-cloud/spring-cloud-circuitbreaker/issues/105
# io.github.resilience4j.circuitbreaker.CircuitBreakerConfig
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      minimumNumberOfCalls: 2
      permittedNumberOfCallsInHalfOpenState: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      slowCallDurationThreshold: 10s
      slowCallRateThreshold: 50

# io.github.resilience4j.ratelimiter.RateLimiterConfig
resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 30s
      cancelRunningFuture: false

spring:
  sleuth:
    # case-sensitive for sleuth
    baggage:
      remote-fields: [ "x-context-ip", "x-context-locale", "x-context-user-id" ]
      correlation-fields: [ "x-context-ip", "x-context-user-id" ]

  cloud:
    # TODO https://github.com/spring-cloud/spring-cloud-commons/issues/747
    loadbalancer:
      retry:
        enabled: true
        avoid-previous-instance: true

    # static uri
    discovery.client.simple.instances:
      test:
        - uri: https://notfound1.xx
        - uri: https://notfound2.google.com

    gateway:
      # enable global cors in config
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'
            max-age: 3600

      default-filters:
        - name: CustomRetry
          args:
            # the retry exceptions regardless of operation
            exceptions:
              - java.io.IOException
              - org.springframework.cloud.gateway.support.NotFoundException
              - io.github.resilience4j.circuitbreaker.CallNotPermittedException
      routes:
        - id: test
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
            - CustomCircuitBreaker